#!/bin/bash
# MQTT Test Scripts for RapidReach Firmware

echo "=== RapidReach MQTT Test Scripts ==="
echo ""
echo "Available commands:"
echo "1. Subscribe to all RapidReach topics:"
echo "   mosquitto_sub -h mosquitto -t 'rapidreach/#' -v"
echo ""
echo "2. Subscribe to heartbeat only:"
echo "   mosquitto_sub -h mosquitto -t 'rapidreach/heartbeat' -v"
echo ""
echo "3. Publish a test message:"
echo "   mosquitto_pub -h mosquitto -t 'rapidreach/test' -m 'Hello from Docker'"
echo ""
echo "4. Monitor connection status:"
echo "   mosquitto_sub -h mosquitto -t 'rapidreach/status' -v"
echo ""
echo "5. Send commands to device (if implemented):"
echo "   mosquitto_pub -h mosquitto -t 'rapidreach/cmd/reboot' -m '1'"
echo ""
echo "=== Usage Examples ==="
echo "# Start monitoring all messages:"
echo "mosquitto_sub -h mosquitto -t 'rapidreach/#' -v"
echo ""
echo "# In another terminal, publish test messages:"
echo "mosquitto_pub -h mosquitto -t 'rapidreach/test' -m 'Docker test message'"
echo ""
