# Install MetalLB first:
# kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/manifests/metallb-native.yaml
# Wait for pods to be ready: kubectl wait --namespace metallb-system --for=condition=ready pod --selector=app=metallb --timeout=90s
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: rapidreach-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.2.79/32  # k3s host IP for MQTT broker
  - 192.168.2.80-192.168.2.85  # Range for future services
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: rapidreach-l2
  namespace: metallb-system
spec:
  ipAddressPools:
  - rapidreach-pool
